package se355final.ProtobufRPCs;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/se355final/MessageService.proto

public final class MessageService {
  private MessageService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/java/se355final/MessageServic" +
      "e.proto\"K\n\007Message\022\024\n\007message\030\001 \001(\tH\000\210\001\001" +
      "\022\023\n\006number\030\002 \001(\005H\001\210\001\001B\n\n\010_messageB\t\n\007_nu" +
      "mberB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Message", "Number", "Message", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
