package se355final.ProtobufRPCs;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/se355final/MessageService.proto

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int32 number = 2;</code>
   * @return Whether the number field is set.
   */
  boolean hasNumber();
  /**
   * <code>optional int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();
}
